### ISSUE TITLE
MS16-032 Checks Need Work

### ISSUE THREAD

**Issue by recrudesce** [rasta-mouse/Sherlock#1]
So, couple of things that need to be added to MS16-032

1. Check CPU core number, as it requires 2+ to function
2. It's only vulnerable between the following versions:

- Win Vista and 2008: Less than **6.0.6002.19598**
- Win Vista and 2008: Between **6.0.6002.23000** and **6.0.6002.23909**
- Win 7 and 2008R2: Less than **6.1.7601.19148**
- Win 7 and 2008R2: Between **6.1.7601.23000** and **6.1.7601.23347**
- 8.1 & 2012R2: Less than **6.3.9600.18230**
- Win 2012: Less than **6.2.9200.17649**
- Win 2012: Between **6.2.9200.21000** and **6.2.9200.21767**
- Win 10: Less than **10.0.10240.16724**
- Win 10 Version 1511: Between **10.0.10586.0** and **10.0.10586.161**

**Comment by rasta-mouse** [comment]
#2
